"""Read-only reader for the strategy parameter-spec registry
(`05_REGISTRY/STRATEGY_PARAM_SPECS.json`, generated by
`03_QUANTLENS/tools/build_strategy_param_specs.py`).

Surfaces, per strategy, the OPTIMIZABLE search grid, the case-count arithmetic,
and the HARDCODED (fixed, not swept) knobs so the Strategy Detail page can show
exactly what is and is not tuned. Never writes, never executes; tolerates an
absent/invalid file with a structured empty state.
"""
from __future__ import annotations

import json
from pathlib import Path
from typing import Any

from .paths import canonicalize, default_mcc_root

REGISTRY_REL_PATH = Path("05_REGISTRY") / "STRATEGY_PARAM_SPECS.json"


def _empty(reason: str) -> dict[str, Any]:
    return {
        "available": False,
        "reason": reason,
        "universe": {},
        "execution_model": {},
        "library_totals": {},
        "strategies": [],
        "by_id": {},
        "count": 0,
    }


def build_param_specs(mcc_root: str | Path | None = None) -> dict[str, Any]:
    root = canonicalize(mcc_root or default_mcc_root())
    path = root / REGISTRY_REL_PATH
    if not path.exists():
        return _empty("registry_not_found")
    try:
        raw = json.loads(path.read_text(encoding="utf-8"))
    except Exception as exc:  # malformed JSON must not break the snapshot
        return _empty(f"json_error: {exc}")
    if not isinstance(raw, dict):
        return _empty("registry_not_object")

    strategies_in = raw.get("strategies")
    strategies: list[dict[str, Any]] = []
    by_id: dict[str, dict[str, Any]] = {}
    if isinstance(strategies_in, list):
        for s in strategies_in:
            if not isinstance(s, dict):
                continue
            sid = str(s.get("strategy_id") or "").strip()
            if not sid:
                continue
            entry = {
                "strategy_id": sid,
                "origin": s.get("origin", "core"),
                "validation_status": s.get("validation_status"),
                "grid_size": s.get("grid_size"),
                "optimizable": s.get("optimizable", {}) if isinstance(s.get("optimizable"), dict) else {},
                "cases_full_universe": s.get("cases_full_universe"),
                "cases_formula": s.get("cases_formula", ""),
                "annotation_status": s.get("annotation_status", "todo"),
                "grid_rationale": s.get("grid_rationale", ""),
                "fixed_knobs": s.get("fixed_knobs", []) if isinstance(s.get("fixed_knobs"), list) else [],
                "missing_knobs": s.get("missing_knobs", []) if isinstance(s.get("missing_knobs"), list) else [],
                "mtc_v2_parity": s.get("mtc_v2_parity", {}),
            }
            strategies.append(entry)
            by_id[sid] = entry

    return {
        "available": True,
        "source": REGISTRY_REL_PATH.as_posix(),
        "generated_utc": raw.get("generated_utc"),
        "read_only": True,
        "phase_legend": raw.get("phase_legend", {}) if isinstance(raw.get("phase_legend"), dict) else {},
        "universe": raw.get("universe", {}) if isinstance(raw.get("universe"), dict) else {},
        "execution_model": raw.get("execution_model", {}) if isinstance(raw.get("execution_model"), dict) else {},
        "library_totals": raw.get("library_totals", {}) if isinstance(raw.get("library_totals"), dict) else {},
        "strategies": strategies,
        "by_id": by_id,
        "count": len(strategies),
    }
