"""
Compare TradingView Supertrend debug export with Python's Supertrend internals.

Usage:
    python scripts/compare_supertrend.py <tv_export_csv> <case_json>

The TV export CSV is generated by:
  1. Adding pine_debug_supertrend.pine indicator to TV chart
  2. Right-click -> Export chart data -> Save CSV

This script:
  1. Loads TV export and Python debug data
  2. Merges by timestamp
  3. Finds the FIRST bar where values diverge
  4. Prints diff details for that bar and the previous bar
  5. Shows top 20 largest diffs sorted by |diff|
"""

import sys
import json
import pandas as pd
import numpy as np
from pathlib import Path

# Add project root to path
sys.path.insert(0, str(Path(__file__).resolve().parent.parent / "src"))


def load_tv_export(csv_path: str) -> pd.DataFrame:
    """Load TradingView's 'Export chart data' CSV."""
    df = pd.read_csv(csv_path)

    # TV export has a 'time' column in various formats
    # Try to find the time/date column
    time_col = None
    for col in df.columns:
        if 'time' in col.lower() or 'date' in col.lower():
            time_col = col
            break

    if time_col is None:
        # First column is usually the timestamp
        time_col = df.columns[0]

    df['timestamp'] = pd.to_datetime(df[time_col])
    if df['timestamp'].dt.tz is not None:
        df['timestamp'] = df['timestamp'].dt.tz_localize(None)
    df = df.set_index('timestamp').sort_index()

    # Normalize column names (TV export may have spaces, prefixes, etc.)
    col_map = {}
    for col in df.columns:
        clean = col.strip().lower()
        # Remove common prefixes
        for prefix in ['debug supertrend internals: ', 'debug_supertrend_internals_']:
            if clean.startswith(prefix):
                clean = clean[len(prefix):]
        clean = clean.replace(' ', '_')
        col_map[col] = f'tv_{clean}'
    df = df.rename(columns=col_map)

    return df


def load_python_debug(case_path: str) -> pd.DataFrame:
    """Load Python's Supertrend debug CSV."""
    with open(case_path) as f:
        case = json.load(f)

    cfg = case["config"]
    st = cfg["supertrend"]
    dataset_path = Path(case_path).resolve().parent.parent.parent / "data" / case["dataset"]

    print(f"Loading Python dataset: {dataset_path}")
    df = pd.read_parquet(dataset_path)

    # Handle column naming
    if 'timestamp' in df.columns:
        df['timestamp'] = pd.to_datetime(df['timestamp'])
        df = df.set_index('timestamp').sort_index()
    elif 'datetime' in df.columns:
        df['datetime'] = pd.to_datetime(df['datetime'])
        df = df.set_index('datetime').sort_index()

    if df.index.tz is not None:
        df.index = df.index.tz_localize(None)

    # Use full available data as preroll
    start = pd.Timestamp(case["start_date"])
    end = pd.Timestamp(case["end_date"]) + pd.Timedelta(days=1)
    preroll_days = case.get("preroll_days", 365)
    preroll_start = start - pd.Timedelta(days=preroll_days)

    df_window = df.loc[preroll_start:end].copy()
    print(f"  Window: {len(df_window)} bars")

    # Compute HA
    from engine.indicators import heikin_ashi, atr, tr, rma

    use_ha = st.get("use_ha", True)
    if use_ha:
        ha_open, ha_high, ha_low, ha_close = heikin_ashi(
            df_window['open'], df_window['high'], df_window['low'], df_window['close']
        )
    else:
        ha_open = df_window['open']
        ha_high = df_window['high']
        ha_low = df_window['low']
        ha_close = df_window['close']

    # Compute ATR
    atr_val = atr(ha_high, ha_low, ha_close, st["atr_len"])

    # Compute TR manually (matching Pine's explicit formula)
    ha_prev_close = ha_close.shift(1)
    # On bar 0, Pine uses nz(haClose[1], haClose) = haClose
    ha_prev_close.iloc[0] = ha_close.iloc[0]
    ha_tr_manual = pd.concat([
        ha_high - ha_low,
        (ha_high - ha_prev_close).abs(),
        (ha_low - ha_prev_close).abs()
    ], axis=1).max(axis=1)

    # Compute RMA of TR
    st_atr_manual = rma(ha_tr_manual, st["atr_len"])

    # Compute Supertrend bands with single-pass loop (matching Pine exactly)
    factor = st["factor"]
    use_wicks = st.get("use_wicks", True)

    src = (ha_high + ha_low) / 2.0
    atr_scaled = factor * st_atr_manual
    h_eff = ha_high if use_wicks else ha_close
    l_eff = ha_low if use_wicks else ha_close
    is_doji = (ha_open == ha_close) & (ha_open == ha_low) & (ha_open == ha_high)

    n = len(df_window)
    long_stop = np.full(n, np.nan)
    short_stop = np.full(n, np.nan)
    long_stop_prev_arr = np.full(n, np.nan)
    short_stop_prev_arr = np.full(n, np.nan)
    direction = np.full(n, 0, dtype=int)

    # Convert to numpy
    src_v = src.values
    atr_s_v = atr_scaled.values
    h_eff_v = h_eff.values
    l_eff_v = l_eff.values
    is_doji_v = is_doji.values

    ls_raw = (src - atr_scaled).values
    ss_raw = (src + atr_scaled).values

    prev_dir = 1
    for i in range(n):
        # Long stop
        curr_long = ls_raw[i]
        if np.isnan(curr_long):
            long_stop[i] = np.nan
            long_stop_prev_arr[i] = np.nan
        else:
            prev_long = long_stop[i - 1] if i > 0 and not np.isnan(long_stop[i - 1]) else curr_long
            long_stop_prev_arr[i] = prev_long
            if curr_long > 0:
                if is_doji_v[i]:
                    long_stop[i] = prev_long
                else:
                    prev_l = l_eff_v[i - 1] if i > 0 else np.nan
                    if not np.isnan(prev_l) and prev_l > prev_long:
                        long_stop[i] = max(curr_long, prev_long)
                    else:
                        long_stop[i] = curr_long
            else:
                long_stop[i] = prev_long

        # Short stop
        curr_short = ss_raw[i]
        if np.isnan(curr_short):
            short_stop[i] = np.nan
            short_stop_prev_arr[i] = np.nan
        else:
            prev_short = short_stop[i - 1] if i > 0 and not np.isnan(short_stop[i - 1]) else curr_short
            short_stop_prev_arr[i] = prev_short
            if curr_short > 0:
                if is_doji_v[i]:
                    short_stop[i] = prev_short
                else:
                    prev_h = h_eff_v[i - 1] if i > 0 else np.nan
                    if not np.isnan(prev_h) and prev_h < prev_short:
                        short_stop[i] = min(curr_short, prev_short)
                    else:
                        short_stop[i] = curr_short
            else:
                short_stop[i] = prev_short

        # Direction
        lp = long_stop[i - 1] if i > 0 and not np.isnan(long_stop[i - 1]) else long_stop[i]
        sp = short_stop[i - 1] if i > 0 and not np.isnan(short_stop[i - 1]) else short_stop[i]

        if prev_dir == -1 and h_eff_v[i] > sp:
            curr_dir = 1
        elif prev_dir == 1 and l_eff_v[i] < lp:
            curr_dir = -1
        else:
            curr_dir = prev_dir

        direction[i] = curr_dir
        prev_dir = curr_dir

    # Build result DataFrame
    result = pd.DataFrame({
        'py_ha_open': ha_open.values,
        'py_ha_high': ha_high.values,
        'py_ha_low': ha_low.values,
        'py_ha_close': ha_close.values,
        'py_ha_tr': ha_tr_manual.values,
        'py_st_atr': st_atr_manual.values,
        'py_st_src': src_v,
        'py_st_atr_scaled': atr_s_v,
        'py_long_stop': long_stop,
        'py_short_stop': short_stop,
        'py_long_stop_prev': long_stop_prev_arr,
        'py_short_stop_prev': short_stop_prev_arr,
        'py_st_dir': direction,
        'py_h_eff': h_eff_v,
        'py_l_eff': l_eff_v,
        'py_is_doji': is_doji_v.astype(int),
        'py_raw_open': df_window['open'].values,
        'py_raw_high': df_window['high'].values,
        'py_raw_low': df_window['low'].values,
        'py_raw_close': df_window['close'].values,
    }, index=df_window.index)
    result.index.name = 'timestamp'

    return result


def find_divergence(tv: pd.DataFrame, py: pd.DataFrame, start_date: str = None):
    """Merge TV and Python data, find first divergence."""

    # Merge on timestamp
    merged = tv.join(py, how='inner')
    print(f"\nMerged rows: {len(merged)}")

    if start_date:
        # Focus on period from 1 day before start_date
        focus_start = pd.Timestamp(start_date) - pd.Timedelta(days=1)
        merged = merged.loc[focus_start:]
        print(f"  Focused from {focus_start}: {len(merged)} rows")

    # Define comparison pairs: (tv_col, py_col, tolerance)
    pairs = [
        ('tv_ha_open', 'py_ha_open', 0.1),
        ('tv_ha_high', 'py_ha_high', 0.1),
        ('tv_ha_low', 'py_ha_low', 0.1),
        ('tv_ha_close', 'py_ha_close', 0.1),
        ('tv_ha_tr', 'py_ha_tr', 0.1),
        ('tv_st_atr', 'py_st_atr', 0.1),
        ('tv_st_src', 'py_st_src', 0.1),
        ('tv_st_atr_scaled', 'py_st_atr_scaled', 0.5),
        ('tv_long_stop', 'py_long_stop', 0.5),
        ('tv_short_stop', 'py_short_stop', 0.5),
        ('tv_st_dir', 'py_st_dir', 0.0),
        ('tv_h_eff', 'py_h_eff', 0.1),
        ('tv_l_eff', 'py_l_eff', 0.1),
    ]

    # Check which columns exist
    available_pairs = []
    for tv_col, py_col, tol in pairs:
        if tv_col in merged.columns and py_col in merged.columns:
            available_pairs.append((tv_col, py_col, tol))
        else:
            missing = []
            if tv_col not in merged.columns:
                missing.append(f"TV:{tv_col}")
            if py_col not in merged.columns:
                missing.append(f"PY:{py_col}")
            print(f"  WARNING: Missing columns {missing}")

    if not available_pairs:
        print("ERROR: No matching columns found!")
        print(f"  TV columns: {[c for c in merged.columns if c.startswith('tv_')]}")
        print(f"  PY columns: {[c for c in merged.columns if c.startswith('py_')]}")
        return

    # Find first divergence
    print("\n=== FIRST DIVERGENCE ===")
    first_div_bar = None
    first_div_col = None
    first_div_diff = None

    for tv_col, py_col, tol in available_pairs:
        diff = (merged[tv_col] - merged[py_col]).abs()
        divergent = diff > tol
        valid = merged[tv_col].notna() & merged[py_col].notna()
        first_idx = divergent[valid & divergent].first_valid_index()
        if first_idx is not None:
            if first_div_bar is None or first_idx < first_div_bar:
                first_div_bar = first_idx
                first_div_col = (tv_col, py_col)
                first_div_diff = diff.loc[first_idx]

    if first_div_bar is None:
        print("  NO DIVERGENCE FOUND! All values match within tolerance.")
        return

    print(f"  First divergence at: {first_div_bar}")
    print(f"  Column: {first_div_col[0]} vs {first_div_col[1]}")
    print(f"  Diff: {first_div_diff:.6f}")

    # Show details for first divergence bar and previous bar
    div_pos = merged.index.get_loc(first_div_bar)
    show_start = max(0, div_pos - 2)
    show_end = min(len(merged), div_pos + 3)

    print(f"\n=== BARS AROUND FIRST DIVERGENCE ===")
    for i in range(show_start, show_end):
        idx = merged.index[i]
        marker = " *** FIRST DIV ***" if idx == first_div_bar else ""
        print(f"\n  Bar {i} ({idx}){marker}")
        for tv_col, py_col, tol in available_pairs:
            tv_val = merged[tv_col].iloc[i]
            py_val = merged[py_col].iloc[i]
            d = abs(tv_val - py_val) if pd.notna(tv_val) and pd.notna(py_val) else float('nan')
            flag = " <-- DIFF!" if d > tol else ""
            name = tv_col.replace('tv_', '')
            print(f"    {name:20s}: TV={tv_val:>14.4f}  PY={py_val:>14.4f}  diff={d:>10.4f}{flag}")

    # Top 20 largest diffs
    print(f"\n=== TOP 20 LARGEST DIFFS ===")
    all_diffs = []
    for tv_col, py_col, tol in available_pairs:
        diff = (merged[tv_col] - merged[py_col]).abs()
        valid = merged[tv_col].notna() & merged[py_col].notna()
        max_diff_idx = diff[valid].idxmax()
        max_diff_val = diff[valid].max()
        if pd.notna(max_diff_val):
            all_diffs.append((max_diff_val, max_diff_idx, tv_col, py_col))

    all_diffs.sort(key=lambda x: x[0], reverse=True)
    for d, idx, tv_col, py_col in all_diffs[:20]:
        name = tv_col.replace('tv_', '')
        tv_val = merged.loc[idx, tv_col]
        py_val = merged.loc[idx, py_col]
        print(f"  {name:20s} at {idx}: TV={tv_val:>14.4f}  PY={py_val:>14.4f}  |diff|={d:>10.4f}")


def main():
    if len(sys.argv) < 3:
        print("Usage: python scripts/compare_supertrend.py <tv_export_csv> <case_json>")
        print()
        print("Steps:")
        print("  1. Add pine_debug_supertrend.pine to your TV chart (BTCUSDT.P 15m)")
        print("  2. Right-click chart -> Export chart data -> Save CSV")
        print("  3. Run: python scripts/compare_supertrend.py <exported.csv> configs/cases/dec2025_parity.json")
        sys.exit(1)

    tv_csv = sys.argv[1]
    case_json = sys.argv[2]

    # Optional start_date filter
    with open(case_json) as f:
        case = json.load(f)
    start_date = case.get("start_date")

    print(f"Loading TV export: {tv_csv}")
    tv = load_tv_export(tv_csv)
    print(f"  TV rows: {len(tv)}")
    print(f"  TV columns: {list(tv.columns)}")

    print(f"\nLoading Python debug from: {case_json}")
    py = load_python_debug(case_json)
    print(f"  PY rows: {len(py)}")

    find_divergence(tv, py, start_date)


if __name__ == "__main__":
    main()
