"""Public API for the MTC contracts package."""

from .admission import (
    AdmissionAuthority,
    AdmissionDecision,
    AdmissionDecisionType,
    EligibilityCheckResult,
    EligibilityState,
    EligibilityVerdictSet,
    VerdictOutcome,
)
from .base import CONTRACT_VERSION
from .execution import (
    EvidenceGapRecord,
    EvidenceWindow,
    EvidenceWindowStatus,
    FreshnessDomain,
    FreshnessEvent,
    FreshnessState,
    GuardianDecision,
    GuardianOutcome,
    LifecycleEvent,
    LifecycleWriterClass,
    ReconciliationMode,
    ReconciliationRecord,
    ReconciliationStatus,
)
from .identity import (
    canonical_json,
    compute_deployment_identity_hash,
    compute_evaluation_run_hash,
    compute_family_id,
    compute_package_hash,
    make_candidate_id,
    make_run_id,
    make_trial_id,
)
from .lineage import (
    Environment,
    EnvironmentLineage,
    EvidenceIdentity,
    UnsimulatedControl,
)
from .orders import (
    Authorization,
    ExitIntent,
    OrderAction,
    OrderIntent,
    QuantitySemantics,
    StopSemantics,
    TakeProfitLeg,
)
from .package import AccountSnapshot, InstrumentMetadata, StrategyPackage
from .protocol import (
    ContractHandshake,
    DeterministicSizingBatch,
    MissingRuleRecord,
    MissingRuleStatus,
)
from .risk import (
    AllocationPolicy,
    GuardianPolicy,
    GuardianVetoClass,
    RiskBucket,
    RiskBucketMember,
)
from .sizing import (
    BoundSizingIntent,
    SizingMethod,
    SizingRequest,
    SizingSourceClass,
    VolatilityTargetParams,
)
from .trials import ArtifactManifest, TrialRecord

__version__ = CONTRACT_VERSION

__all__ = [
    "CONTRACT_VERSION",
    "AccountSnapshot",
    "AdmissionAuthority",
    "AdmissionDecision",
    "AdmissionDecisionType",
    "AllocationPolicy",
    "ArtifactManifest",
    "Authorization",
    "BoundSizingIntent",
    "ContractHandshake",
    "DeterministicSizingBatch",
    "EligibilityCheckResult",
    "EligibilityState",
    "EligibilityVerdictSet",
    "Environment",
    "EnvironmentLineage",
    "EvidenceGapRecord",
    "EvidenceIdentity",
    "EvidenceWindow",
    "EvidenceWindowStatus",
    "ExitIntent",
    "FreshnessDomain",
    "FreshnessEvent",
    "FreshnessState",
    "GuardianDecision",
    "GuardianOutcome",
    "GuardianPolicy",
    "GuardianVetoClass",
    "InstrumentMetadata",
    "LifecycleEvent",
    "LifecycleWriterClass",
    "MissingRuleRecord",
    "MissingRuleStatus",
    "OrderAction",
    "OrderIntent",
    "QuantitySemantics",
    "ReconciliationMode",
    "ReconciliationRecord",
    "ReconciliationStatus",
    "RiskBucket",
    "RiskBucketMember",
    "SizingMethod",
    "SizingRequest",
    "SizingSourceClass",
    "StopSemantics",
    "StrategyPackage",
    "TakeProfitLeg",
    "TrialRecord",
    "UnsimulatedControl",
    "VerdictOutcome",
    "VolatilityTargetParams",
    "__version__",
    "canonical_json",
    "compute_deployment_identity_hash",
    "compute_evaluation_run_hash",
    "compute_family_id",
    "compute_package_hash",
    "make_candidate_id",
    "make_run_id",
    "make_trial_id",
]
