"""Generate fixtures/data.js from the fixtures/*.json files.

Run from anywhere; paths resolve relative to this file:

    python fixtures/build_data_js.py

Reads workers.json, intents.json and market_context.json, validates each as
JSON, and emits data.js assigning window.FIXTURES so the prototype works from
file:// with no fetch/XHR. The JSON files are the canonical fixture source;
data.js is generated output — do not edit it by hand.

Output is pure ASCII (ensure_ascii) so the emitted literal is a safe subset of
JavaScript (avoids U+2028/U+2029 string pitfalls).
"""

import json
from pathlib import Path

HERE = Path(__file__).resolve().parent
SOURCES = ["workers.json", "intents.json", "market_context.json"]
KEYS = ["workers", "intents", "market_context"]


def main() -> int:
    data = {}
    for src in SOURCES:
        path = HERE / src
        data[KEYS[SOURCES.index(src)]] = json.loads(path.read_text(encoding="utf-8"))
        print(f"validated {src}")

    payload = json.dumps(data, indent=2, ensure_ascii=True, sort_keys=False)
    banner = (
        "/* Generated by fixtures/build_data_js.py from the fixtures/*.json files.\n"
        " * Do not edit by hand — edit the JSON files and re-run the script.\n"
        " * window.FIXTURES is the single input of index.html; the page performs\n"
        " * no network access of any kind. */\n"
    )
    out = HERE / "data.js"
    out.write_text(banner + "window.FIXTURES = " + payload + ";\n", encoding="utf-8")
    print(f"wrote {out.name} ({out.stat().st_size} bytes)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
