"""
MTC Dashboard Utilities.

This package provides reusable components, styles, and session 
management for the MTC Streamlit dashboard.
"""

from .styles import get_custom_css, apply_styles
from .components import (
    metric_card,
    metric_row,
    kpi_section,
    section_header,
    divider,
    card_container,
    card_container_end,
    info_box,
    success_box,
    warning_box,
    error_box,
    dataframe_display,
    table_display,
    loading_spinner,
    progress_bar,
    config_section,
    sidebar_section,
    sidebar_nav,
    sidebar_metric,
    chart_container,
    chart_container_end,
    code_block,
    status_indicator,
    status_list,
    tab_container,
    metrics_tabs,
)
from .session import (
    init_session,
    reset_backtest_state,
    reset_optimization_state,
    clear_cache,
    get_backtest_dataset,
    get_backtest_results,
    get_current_page,
    get_datasets,
    set_backtest_dataset,
    set_backtest_results,
    set_current_page,
    set_datasets,
    save_config_to_session,
    load_config_from_session,
    get_data_dir,
    get_exports_dir,
    get_logs_dir,
    ensure_directories,
    get_dataset_count,
    get_export_count,
)

__all__ = [
    # Styles
    "get_custom_css",
    "apply_styles",
    # Components
    "metric_card",
    "metric_row",
    "kpi_section",
    "section_header",
    "divider",
    "card_container",
    "card_container_end",
    "info_box",
    "success_box",
    "warning_box",
    "error_box",
    "dataframe_display",
    "table_display",
    "loading_spinner",
    "progress_bar",
    "config_section",
    "sidebar_section",
    "sidebar_nav",
    "sidebar_metric",
    "chart_container",
    "chart_container_end",
    "code_block",
    "status_indicator",
    "status_list",
    "tab_container",
    "metrics_tabs",
    # Session
    "init_session",
    "reset_backtest_state",
    "reset_optimization_state",
    "clear_cache",
    "get_backtest_dataset",
    "get_backtest_results",
    "get_current_page",
    "get_datasets",
    "set_backtest_dataset",
    "set_backtest_results",
    "set_current_page",
    "set_datasets",
    "save_config_to_session",
    "load_config_from_session",
    "get_data_dir",
    "get_exports_dir",
    "get_logs_dir",
    "ensure_directories",
    "get_dataset_count",
    "get_export_count",
]
